# Generated by Django 5.1.7 on 2025-03-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('rating', models.CharField(choices=[(0, 'dislike'), (1, 'like')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
