# Generated by Django 5.1.7 on 2025-03-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0004_alter_ratingsmodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingsmodel',
            name='rating',
            field=models.IntegerField(verbose_name=[(0, 'dislike'), (1, 'like')]),
        ),
    ]
