# Generated by Django 5.1.7 on 2025-04-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0005_alter_ratingsmodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentMetaDataModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('luid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('parent_luid', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ratingsmodel',
            name='rating',
            field=models.IntegerField(choices=[(0, 'dislike'), (1, 'like')], default=0),
        ),
    ]
