# Generated by Django 5.1.7 on 2025-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0006_contentmetadatamodel_alter_ratingsmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmetadatamodel',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
