# Generated by Django 5.1.7 on 2025-04-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0007_contentmetadatamodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmetadatamodel',
            name='hide_from_users',
            field=models.TextField(blank=True, null=True),
        ),
    ]
