# Generated by Django 5.1.7 on 2025-04-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0008_contentmetadatamodel_hide_from_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingsmodel',
            name='item_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
