# Generated by Django 5.1.7 on 2025-04-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableau', '0009_ratingsmodel_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmetadatamodel',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
