POD_URL = "YOUR_TABLEAU_SERVER_URL"
SITE_NAME = "YOUR_SITE_NAME"
PAT_NAME = "YOUR_PAT_NAME"
PAT_SECRET = "YOUR_PAT_SECRET"

CONNECTED_APP_NAME = "YOUR_CONNECTED_APP_NAME"
CONNECTED_APP_CLIENT_ID = "YOUR_CONNECTED_APP_CLIENT_ID"
CONNECTED_APP_SECRET_ID = "YOUR_CONNECTED_APP_SECRET_ID"
CONNECTED_APP_SECRET_VALUE = "YOUR_CONNECTED_APP_SECRET_VALUE"
